import assets from "./assets";

const NFTData = [
  {
    id: "NFT-01",
    name: "Headset",
    title: "T900 pro max modern headset",
    price: 4.25,
    description:
      "The action painter abstract expressionists were directly influenced by automatism. Pollock channelled this into producing gestural. The action painter abstract expressionists were directly influenced by automatism. Pollock channelled this into producing gestural. The action painter abstract expressionists were directly influenced by automatism. Pollock channelled this into producing gestural.",
    url: assets.headset01,
    bids: [
      {
        id: "BID-11",
        name: "this dummy data annoyed me a lot",
        price: 4.25,
        url: assets.person02,
        date: "December 12, 2019 at 12:10 PM",
      },
      {
        id: "BID-12",
        name: "asus gamming pc",
        price: 4.5,
        url: assets.person03,
        date: "December 27, 2019 at 1:50 PM",
      },
      {
        id: "BID-13",
        name: "Acer laptop",
        price: 4.75,
        url: assets.person04,
        date: "December 31, 2019 at 3:50 PM",
      },
    ],
  },
  {
    id: "NFT-02",
    name: "Desktop",
    title: "Moder gaming desktop",
    price: 7.25,
    description:
      "The action painter abstract expressionists were directly influenced by automatism. Pollock channelled this into producing gestural. Nulla sed velit erat vitae leo sem inceptos diam fames arcu hendrerit, quis ultrices in eleifend posuere ipsum conubia porttitor felis.",
    url: assets.desktop01,
    bids: [
      {
        id: "BID-21",
        name: "Smart for iPhone",
        price: 7.05,
        url: assets.person04,
        date: "December 12, 2019 at 12:10 PM",
      },
    ],
  },
  {
    id: "NFT-03",
    name: "Modern Man Gadgets ",
    title: "Disco Wireless appliance",
    price: 95.25,
    description: "The action painter im nascetur. ",
    url: assets.gadgets,
    bids: [
      {
        id: "BID-31",
        name: "Eva Bag",
        price: 95.25,
        url: assets.watch,
        date: "December 12, 2019 at 12:10 PM",
      },
      {
        id: "BID-32",
        name: "powerfull power bank",
        price: 95.5,
        url: assets.headset01,
        date: "December 27, 2019 at 1:50 PM",
      },
    ],
  },
  {
    id: "NFT-04",
    name: "Smart Watch",
    title: "Universial Portable smart watch 200 mAh",
    price: 54.25,
    description: "The action painter im nascetur. ",
    url: assets.VR01,
    bids: [
      {
        id: "BID-43",
        name: "Smart Camera",
        price: 55.15,
        url: assets.joystick01,
        date: "December 31, 2019 at 3:50 PM",
      },
      {
        id: "BID-44",
        name: "Wireless airpods",
        price: 54.15,
        url: assets.VR02,
        date: "December 31, 2019 at 3:50 PM",
      },
    ],
  },
  {
    id: "NFT-05",
    name: "Colorful joystick",
    title: "Modern long term functional joystick",
    price: 10.25,
    description: "Modern long term functional joystick",
    url: assets.joystick01,
    bids: [
      {
        id: "BID-51",
        name: "Solar Power",
        price: 10.25,
        url: assets.VR03,
        date: "December 12, 2019 at 12:10 PM",
      },
    ],
  },
  {
    id: "NFT-06",
    name: "Black Josystick",
    title: "Modern long term functional joystick",
    price: 20.25,
    description: "Modern long term functional joystick. ",
    url: assets.joystick02,
    bids: [
      {
        id: "BID-62",
        name: "Asus",
        price: 20.5,
        url: assets.joystick02,
        date: "December 27, 2019 at 1:50 PM",
      },
      {
        id: "BID-63",
        name: "modern keyboard ",
        title: "modern keyboard your computer ",
        price: 20.75,
        url: assets.joystick02,
        date: "December 31, 2019 at 3:50 PM",
      },
      {
        id: "BID-64",
        name: "Lenovo",
        price: 21.25,
        url: assets.joystick02,
        date: "December 31, 2019 at 3:50 PM",
      },
      {
        id: "BID-65",
        name: "Dell laptop",
        price: 7.25,
        url: assets.joystick02,
        date: "December 31, 2019 at 3:50 PM",
      },
    ],
  },
  {
    id: "NFT-07",
    name: "Modern keyboard ",
    title: "Modern keyboard for modern computer systems",
    price: 18.25,
    description: "The action painter im nascetur. ",
    url: assets.VR01,
    bids: [],
  },
  {
    id: "NFT-08",
    name: "Modern keyboard ",
    title: "Modern keyboard for modern computer systems",
    price: 18.25,
    description: "The action painter im nascetur. ",
    url: assets.VR02,
    bids: [],
  },
  {
    id: "NFT-09",
    name: "Modern keyboard ",
    title: "Modern keyboard for modern computer systems",
    price: 18.25,
    description: "The action painter im nascetur. ",
    url: assets.headset03,
    bids: [],
  },
];

export { NFTData };
